### ISSUE TITLE
Gene panels missing?

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/cg#1605] opened 2022-10-24 08:45 UTC
Only the gene panels that have been ordered are visible in the list on the first page and in the filter on the variant page. It is not possible to choose to analyze another panel.

**Comment by dnil** [comment] 2022-10-24 11:26
Thanks! A for effort for converting that list constant to a proper Class though! 😊 👍

**Comment by peterpru** [comment] 2022-10-24 11:28
Hi everyone, this is a bug that arose from a recent PR, as @dnil alluded to. I will start working on this immediately.

@NicoleCMMS, I apologize for the inconvenience. After we fix this, would you like us to rerun the affected cases, so that these panels are included again?

**Comment by NicoleCMMS** [comment] 2022-10-24 11:36
Hi Peter,
That would be great if we could get all of these cases rerun!  Thanks a lot!!
Nicole

Från: Peter Pruisscher ***@***.***>
Skickat: den 24 oktober 2022 13:29
Till: Clinical-Genomics/cg ***@***.***>
Kopia: Nicole Lesko ***@***.***>; Mention ***@***.***>
Ämne: Re: [Clinical-Genomics/cg] Gene panels missing? (Issue #1605)


Hi everyone, this is a bug that arose from a recent PR, as @dnil<https://github.com/dnil> alluded to. I will start working on this immediately.

@NicoleCMMS<https://github.com/NicoleCMMS>, I apologize for the inconvenience. After we fix this, would you like us to rerun the affected cases, so that these panels are included again?

**Comment by sofievonlanthen** [comment] 2022-10-25 14:31
I noticed that same thing this morning. Are you planning to re-run all cases once the issue is fixed? We have specifically one case where I would like to add another panel: 022701400263 (cust004). 

/Sofie

**Comment by peterpru** [comment] 2022-10-26 08:46
Hi @sofievonlanthen, we can definitely rerun all cases, if that is desired. I will now restart the particular case you mention including all the standard panels you normally have access to.

**Comment by NicoleCMMS** [comment] 2022-10-26 09:01
Hi Peter, has the problem been fixed?  It would be really great if we could get all of our cases that have been uploaded from 2022-10-22 and onwards rerun also.
Thanks!
Nicole

**Comment by peterpru** [comment] 2022-10-26 10:08
Hi @NicoleCMMS. The problem has been fixed, and I am now restarting your cases. I will send a delivery notification in the respective tickets of the affected cases.

Best regards, 
Peter

**Comment by northwestwitch** [comment] 2022-10-27 05:14
Hi @peterpru. I've received an email from cust004 ( @sofievonlanthen ) and they have experienced the same issue. Could you restart the analysis of their cases as well ?

**Comment by northwestwitch** [comment] 2022-10-27 05:15
Ah sorry, I haven't read the messages until the end, closing again! :)

**Closed** 2022-10-27 05:15 UTC
Labels: Bug
