### ISSUE TITLE
List finished analyses in the delivery message for data_delivery="analysis"

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/cg#3439] opened 2024-07-17 12:19 UTC
As a prodbioinfo user,
I want the delivery message for cases with analysis as delivery option to state which cases have completed,
So that the customer is informed of which cases in the ticket are actually being delivered.

# Acceptance Criteria

- [ ] The delivery message for cases with `Data delivery = Analysis` included the case(s) that are being delivered.

# Notes

- Template for delivery message:
Single case

```Shell
Hello,﻿
The analysis is now complete for case <case_name>.
The analysis files are currently being uploaded to your inbox on Caesar:
/home/custID/inbox/TICKET_ID
```

Multiple cases from the same ticket:
```Shell
Hello,﻿
The analysis is now complete for cases:
<case_name>
<case_name>
<case_name>
...
The analysis files are currently being uploaded to your inbox on Caesar:
/home/custID/inbox/TICKET_ID
```

- Related user stories: https://github.com/Clinical-Genomics/cg/issues/3312

# Clarification
For deliveries where no scout upload is requested, cases that are delivered are not listed. That is, cases with data_delivery: ANALYSIS and ANALYSIS-FASTQ

**Comment by Vince-janv** [comment] 2024-10-17 12:14
Closing as duplicate of: https://github.com/Clinical-Genomics/cg/issues/3846

**Closed by Vince-janv** 2024-10-17 12:14 UTC
Labels: Enhancement, Gain S, Effort S, Urgency M
