### ISSUE TITLE
bed-version not added to status-db and unable to start cg

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/cg#815] opened 2020-11-03 13:51 UTC
Problem: 
Unable to start balsamic automatically since bed version is missing. I am unsure if this is cg or status-db related so I also tag @patrikgrenfeldt 

```
Case justshrew has following BALSAMIC samples:
SAMPLE ID            TISSUE TYPE          APPLICATION          BED VERSION         
ACC7117A17           tumor                wes                  None                

Could not create config: Application type wes requires a bed file to be analyzed!
Aborted!
```

The samples are provided bait set in LIMS, but this info is missing in status db:
https://clinical-lims.scilifelab.se/clarity/work-complete/159444
https://clinical-api.scilifelab.se/admin/sample/?search=ACC7117A17

Steps to reproduce

  1. `up`
  2.  `cg workflow balsamic start justshrew`

Expected outcome / suggested solution:
Start balsamic

Questions: 
Is this cg, lims, or status-db related?

What needs to be done on the planning meeting:

See https://github.com/Clinical-Genomics/development/blob/master/git/issue-reports.md for more!

**Comment by Mropat** [comment] 2020-11-03 15:20
@keyvanelhami  what is the bair set called in LIMS?
@hassanfa are we missing the panel_bed in the database perhaps?

**Comment by hassanfa** [comment] 2020-11-03 15:31
@Mropat
**Problem is obvious here:** Looking into clinical-api, this sample has no panel bed assigned to it. Thus `cg` fails.

**Solution:** A process upstream is causing the problem. Talk to someone in lab and ask them to make sure assigned capture kit made it through order process to, and then update clinical-api.

**Comment by Mropat** [comment] 2020-11-03 19:22
@hassanfa the panel bed is never set in clinical anyway. We get capture kit from lims (where we know it was it's set) and then we use it look up panel bed in the panel table. So the capture kit in lims isn't asssociated with any bed in clinical.

**Comment by keyvanelhami** [comment] 2020-11-04 07:45
Taking @annaengstrom in the conversation. It seems like the "bed version" is missing in the LIMS step (see red circle below). Is the bed-version added manually or is it provided automatically when choosing bait set ? 

The analysis didn't start automatically and we need to know if this is a bug or human error related.

![Screen Shot 2020-11-04 at 8 42 13 AM](https://user-images.githubusercontent.com/26735714/98082968-eb26d980-1e79-11eb-820e-33bc6078773a.png)

**Comment by annaengstrom** [comment] 2020-11-04 07:55
@mayabrandi this UDF is supposed to be "required", can you check what happened?

**Comment by annaengstrom** [comment] 2020-11-04 08:00
No bug, not human error in this step.
![Screenshot 2020-11-04 at 08 57 29](https://user-images.githubusercontent.com/36469416/98084244-d21f2800-1e7b-11eb-8c21-01126f5f488b.png)

We set the UDF "Bait set" manually, and this step is "required" meaning we cannot go forward without setting it. The filed missing is UDF "Capture Library version". What is this UDF used for in the analysis? As I remember for MIP, it should not be used. How is it set? Previously via order, but this will no longer be correct for analysis. Information about bait set should be picked up from UDF bait set, not capture library version.

**Comment by annaengstrom** [comment] 2020-11-04 08:04
As we set it, UDF "Capture library version" is set by customer in order, for us to know for PAN app tags which panel to use. It should ideally only be information from customer to the lab staff, but should not involve analysis. It seems orderportal somehow is updated... 
@patrikgrenfeldt @elevu is UDF Capture library version in orderportal free text? This is not set by orderform, and only gives reference to website.

**Comment by annaengstrom** [comment] 2020-11-04 08:06
> @Mropat
> **Problem is obvious here:** Looking into clinical-api, this sample has no panel bed assigned to it. Thus `cg` fails.
> 
> **Solution:** A process upstream is causing the problem. Talk to someone in lab and ask them to make sure assigned capture kit made it through order process to, and then update clinical-api.

bait set cannot be set via order, as customer does not know which version we use. The UDF is required in LIMS and we cannot proceed without filling it out

**Comment by keyvanelhami** [comment] 2020-11-04 08:33
I added the capture kit manually `cg set sample ACC7117A17 -kv capture_kit exome_comp_10.1` but still I am unable to start the analysis. @Mropat Any ideas why?

```
SAMPLE ID            TISSUE TYPE          APPLICATION          BED VERSION         
ACC7117A17           tumor                wes                  None                

Could not create config: Application type wes requires a bed file to be analyzed!
```

<img width="729" alt="Screen Shot 2020-11-04 at 9 32 34 AM" src="https://user-images.githubusercontent.com/26735714/98087609-a488ad80-1e80-11eb-80bd-6427e1684ce2.png">

**Comment by Mropat** [comment] 2020-11-04 09:15
> I added the capture kit manually `cg set sample ACC7117A17 -kv capture_kit exome_comp_10.1` but still I am unable to start the analysis. @Mropat Any ideas why?
> 
> ```
> SAMPLE ID            TISSUE TYPE          APPLICATION          BED VERSION         
> ACC7117A17           tumor                wes                  None                
> 
> Could not create config: Application type wes requires a bed file to be analyzed!
> ```
> 
> <img alt="Screen Shot 2020-11-04 at 9 32 34 AM" width="729" src="https://user-images.githubusercontent.com/26735714/98087609-a488ad80-1e80-11eb-80bd-6427e1684ce2.png">

Unfortunately the cg code is not looking at capture kit field and is always fetching it from LIMS. 
A suggestion to solve this temporarily for the samples where it is a problem: provide panel bed name as an argument to `cg workflow balsamic run `  for cases where human error ocurred. This bypassed lims and gets panel path from CG instead

**Comment by keyvanelhami** [comment] 2020-11-04 09:43
Thanks Maria. I have now started the affected cases manually

**Comment by annaengstrom** [comment] 2020-11-04 09:55
Do you know what the initial problem was?

**Comment by keyvanelhami** [comment] 2020-11-04 10:00
I have only started the analysis **manually** while we are investigating the root of this problem. So no, I don't know why this problem happened

**Comment by mayabrandi** [comment] 2020-11-05 09:37
The problem is that then new twist v3 workflow has not been updated in the lims config file in cg. [This PR ](https://github.com/Clinical-Genomics/cg/pull/818)will fix that problem. It is my fault. I forgot to update the config in cg when creating the new workflow.

**Closed** 2020-11-05 11:40 UTC
