### ISSUE TITLE
The analysis results files should be automatically linked to cust INBOX

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/cg#78] opened 2018-02-28 21:23 UTC
Now, analysis result files are linking semi-manually (with the help of bash functions that link the massive amount of files). It would be better to have analysis result files linked automatically.

- [x] add linking from BAM/BAI files to cg (meaning: remove the bash functions)
- [x] add linking from VCF files
- [ ] automate
- [ ] add linking fastq files
 - wgs/wes
 - microbial
 - rna
 - cancer
- [ ] documentation (raw data delivery doc 1060)

see DoD minor

**Comment by henrikstranneheim** [comment] 2020-10-24 10:40
Duplicate of https://github.com/Clinical-Genomics/cg/issues/794. Closing

**Closed by henrikstranneheim** 2020-10-24 10:40 UTC
