### ISSUE TITLE
wishlist - cg delete sample

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/cg#1235] opened 2021-07-08 13:00 UTC
## Description

It is difficult to delete a large number of samples within a case from api and seems not possible in an easy/straight forward way via cli

## Suggested solution

create a cli command to be able to delete samples within a case

## This can be closed when

*Describe what needs to be done for this issue to be closed*

## Blocked by

*If there are any blocking issues/prs/things in this or other repos. Please link to them.*

**Comment by annaengstrom** [comment] 2021-07-08 13:01
@karlnyr

**Comment by annaengstrom** [comment] 2021-07-08 13:10
@karolinstorck

**Comment by Mropat** [comment] 2022-02-25 14:34
@henrikstranneheim @henningonsbring @moahaegglund 
This issue needs help with defining prioritization for the next quarter
If the issue is a highly disruptive bug, it should be fixed immediately and time to delivery estimated
If this can wait for new orderportal, it should be closed

**Comment by henningonsbring** [comment] 2022-02-25 15:10
In the rare situations where this needs to be done I usually find a workaround with some kind of bash loop. But it was many many months ago since I did something like that.

So I say this can wait until new orderportal.

**Comment by Mropat** [comment] 2022-02-25 15:22
Thanks for feedback, will not be implemented in this version of cg

**Closed by Mropat** 2022-02-25 15:22 UTC
Labels: Enhancement, cg, production

**Comment by annaengstrom** [comment] 2022-02-26 09:02
The lab staff (and @annagellerbring probably) would benefit from this, but I guess it can be implemented in the new orderportal.
