### ISSUE TITLE
bug(Fluffy cases are started without all fastq files

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#2580] opened 2023-10-10 06:47 UTC
## Description

In two separate instances, for cases `deepmarten` and `warmcod`, the pipeline initiation occurred without all the necessary fastq files being linked to the directory. This resulted in only a subset of samples being linked, seemingly triggered by the timing of demultiplexing post-processing and the creation of the housekeeper bundle. For instance, in a typical case with 46 samples, only 11 samples were found linked in the `case/fastq` folder on hasta instead of the expected 46. It's worth noting that all samples did receive reads. Manually removing and re-initiating the case folder resolved the issue, successfully linking all fastq files.

## Suggested solution

_TBD_

## This can be closed when

No Fluffy case is started without all the sample files linked to it

## Blocked by

_NA_

**Comment by islean** [comment] 2023-10-10 12:15
So potential causes here are that the finish-all cron job and the Fluffy start-available cron jobs start at precisely coinciding intervals. Couple that with fastq files being commited to Housekeeper on a file basis (rather than e.g. flow cell level), makes for a potential cause. I have created a quick PR to just run the cron jobs out of sync while the root cause is addressed. #2378 will most likely add a precheck ensuring that all fastq files are present, and we should also think about refactoring the commits to Housekeeper upon inclusion.

**Comment by henrikstranneheim** [comment] 2024-02-22 14:56
@islean @karlnyr Done?

**Comment by ChrOertlin** [comment] 2024-07-24 14:23
@karlnyr has this issue re-occured lately or was this solved by the fixes @islean  implemented? Closing this for now, re-open if this still persists.

**Closed by ChrOertlin** 2024-07-24 14:23 UTC
Labels: Bug, Gain L, Effort S, Urgency L, Needs Refinement
