### ISSUE TITLE
clean `scout-finished-cases` has a potential issue with old `solved` cases

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/cg#3064] opened 2024-03-22 15:59 UTC
## Description

Freshly uploaded rerun solved cases have alignment files erroneously cleaned, although their apparent analysis date is correct. Compare cases `cleverpup`, `tendergator` and `tidyimpala`. On load they would all have been sitting around with fresh files and scout status `solved` after re-uploading, since we only change the status back to inactive for cases with status active and archived if they are rerun.
 
## Suggested solution

First, trouble-shoot: primary candidate would be date parsing on output from `scout export cases --json`.

## This can be closed when

Freshly uploaded rerun alignments are not deleted nightly for previously `solved` cases.

# Clarification
The scout cleaning command removes the CRAM file based on time (older than 300 days) or if the case is solved. Hence if a solved case is re-run the file will be removed directly. The CRAM file is stored in the housekeeper bundle on hasta.

The current logic looks at the field `analysis_date` which should be correctly set for re-analysed cases.

**Comment by Vince-janv** [comment] 2024-07-01 12:05
Interesting, that does sound annoying. Do we know why a user would like to re-run a solved case? It sounds like a design-flaw somewhere 🤔

**Comment by dnil** [comment] 2024-07-01 12:33
Yes, the nomenclature of “solving” a genomics investigation is flawed in general. ☺️Life is seldom  that simple. One possibility is the advent of new unexpected symptoms in an rd case, the end of a remission period in leukemia, or perhaps just technical reasons such as wanting a control sample or make a picture for a new report.

One could also say Scout is  it granular enough in the solve situation. I do’nt know if you looked at the three examples provided? For one of the cases, a strong class 3 was answered out as unclear but possibly significant in 2020, and the case marked solved in part to indicate it had been reported non-negative and in part to have the interesting variant show up in matching causatives to try and catch more cases. Fast forward a few years, it’s time to reevaluate the patient for whatever reason. Now the variant is more common in the public dbs, and still no more affected carriers. It was probably benign after all.

**Comment by Vince-janv** [comment] 2024-07-01 14:39
Not knowing exactly how users work in scout, would it make sense to just create a new case with the old samples? Would the users loose any functionality compared to re-running the same case again.

We are striving for unifying re-runs in the future to only go via new cases, and if this can solve this problem it would be one more argument for it

**Comment by dnil** [comment] 2024-07-01 15:26
Yes! There are many reasons we allow a choice between fresh new case for a rerun or saving old data on a case.
With a new case, old comments and variant assertions, variant dismissal - basically all previous user interaction - will have to be looked up on the new case by cross reference to the old case. This is good if the intent is to do a complete new analysis, not so much if the intent is just to check if a pipeline patch solved a problem or panel addition found a new variant. 

The updated sample also does not get stored to loqus as it will be considered duplicated. The old gens run will be overwritten.

To do new cases for all reruns, short terms reruns must be rare, otherwise these would be bad for storage. Also reruns that happen only past file system cleanup will still add to db server storage growth, if the old case is not removed.

Obviously the current system also has a lot of problems, one of them being the increased number of new case runs. 
This is not the place for a full discussion about rerun logic in general. It needs refactoring, but doing new-cases-only stages a value conflict between production resources and customer operator hands-on time. I would suggest something akin to a small risk analysis on this topic to weigh advantages and disadvantages?

In a galaxy far, far away, we may also rekindle the idea of `melter` or `pergamon` and have automated rerun diffs pop into the equation. ☺️

On the surface this appears to be just a small bug in the cleanup logic and its timestamps? There should be e.g. file dates and LIMS/statusdb dates that clearly indicate that the last case rerun is much newer than whatever original run date is used to do the check now?

**Comment by Vince-janv** [comment] 2024-07-02 06:28
Yes, re-runs is definitely something to tackle in the future. Thanks for the clarification I'll put it on our list

**Comment by Vince-janv** [comment] 2024-07-04 08:17
### Technical refinement:
We can easily change (here: cg/cli/clean.py:131)the timestamp to another one if a correct date is provided by the scout export cases output.
@dnil can you provide us such a timestamp that exists on all cases?

### Questions
use `updated_at`?
why can't we use `analysis_date`
Can we use the latest `analysis_dates`?

**Comment by Vince-janv** [comment] 2024-07-04 14:53
The `analysis_date` is the date being used and for all cases you mentioned it seems to be correct. So I wen't back to debugging mode and have not found anything on this bug. Can you provide cases where it has happened?

**Comment by dnil** [comment] 2024-07-04 15:10
I'm sorry, I'm not quite following the logic here? Maybe it's getting a bit late in the day. ☺️ Are you looking for a testing/bug fix verification case perhaps?

All three cases mentioned have been fixed like three months ago with the prod standard procedure for when this happens, i.e. delete and re-upload from scratch. You can search for the perhaps not super enlightening threads regarding these cases on slack or better yet ask the prod team for a recent, or maybe even an unfixed case next time it happens if you wanted a verification one without faking it?

**Comment by Vince-janv** [comment] 2024-08-07 13:35
@Clinical-Genomics/prodbioinfo Can you notify us as soon as this occurs again?

**Comment by Vince-janv** [comment] 2024-08-14 14:49
Closing until reproduced

**Closed by Vince-janv** 2024-08-14 14:49 UTC
Labels: on hold
