### ISSUE TITLE
Glue vcf2cytosure CGH files.

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/cg#200] opened 2018-10-01 07:12 UTC
Contact person: DN

Many clinical geneticists wants to visualise structural variants using legacy visual tools.

**Problem:**
MIP runs vcf2cytosure to generate CGH files. Scout reads the path of these through its config file. Some glue is needed!

See issue [#714](https://github.com/Clinical-Genomics/scout/issues/714) on scout; PR [#972](https://github.com/Clinical-Genomics/scout/pull/972), MIP [#280](https://github.com/Clinical-Genomics/MIP/issues/280) [#518](https://github.com/Clinical-Genomics/MIP/issues/518).

**Steps to reproduce**
Filename found in MIP qc_sample_info.yaml with the key vcf2cytosure on each sample. Scout looks for a key vcf2cytosure in its load config pointing to same file. See e.g. scout admin docs on load-config for an example.

**Suggested solution**
Use **neededrat** as example family.
- In TB: parse out CGH file from MIP sampleInfo
- Add file to HK, key `CGH`
- CG should specify the path to the file in the scout case config for upload

**Expected outcome / suggested solution:**
Scout config files containing vcf2cytosure, and CGH files available on a location and with a permission suitable for download from scout.

**DoD**
- minor
- demo
  run `cg upload scout --print`: should have a CGH file in the output.

**Comment by ingkebil** [comment] 2018-10-02 19:39
As far as I can tell, this is the status of CGH files in the other projects:
- MIP: available in MIP6 ?
- Scout: available sine https://github.com/Clinical-Genomics/scout/pull/972

So, you would only need CG to catch up, is that correct?

**Comment by henrikstranneheim** [comment] 2018-10-03 04:42
Correct

**Comment by emiliaol** [comment] 2018-10-31 14:29
@dnil The feature is now live and we tested if the download actually worked on a case in Scout Stage: Could you please have a look and tell us if this is the file that was intended for this function: https://scout-stage.scilifelab.se/cust002/F0005342

**Comment by dnil** [comment] 2018-10-31 14:46
Thank you - I confirm I could reach a CGH-file for the case from Scout! 👍  
The sample name in the file is a clinical-internal one, not the customer ID, but that is a MIP issue rather than a CG one.

**Comment by dnil** [comment] 2018-10-31 14:52
Also, its big and very compressible (>20x reduction). Will shrink a bit when local database filtering is activated, but still, perhaps worth the effort to compress.

**Comment by patrikgrenfeldt** [comment] 2018-10-31 14:58
Can you open an issue in MIP about the sample name?
BR
Patrik

Den ons 31 okt. 2018 15:47 skrev Daniel Nilsson <notifications@github.com>:

**Comment by dnil** [comment] 2018-10-31 15:10
Ok! [#621](https://github.com/Clinical-Genomics/MIP/issues/621)

**Comment by patrikgrenfeldt** [comment] 2018-10-31 17:05
Awesome! I guess we can consider the cg issue solved?

Den ons 31 okt. 2018 16:14 skrev Daniel Nilsson <notifications@github.com>:

**Comment by ingkebil** [comment] 2018-11-01 06:30
So maybe the questions that should be asked are:
- does MIP get any external ids, e.g. does it rename the IDs in bam and vcf files? (does that matter?)
- it is more convenient to not have to post process files. Does it make sense to have them being passed to MIP?

**Comment by dnil** [comment] 2018-11-01 07:11
Yep! Let's discuss that with @henrikstranneheim and @jemten. I'm at CG today. But as far as the original user story went, this issue is closed, and a new one is brewing.

**Comment by ingkebil** [comment] 2018-11-05 20:10
Gzip sounds fine. Do you want us to create an extra issue for that?

**Comment by dnil** [comment] 2019-01-10 15:06
We'll skip gzip for now, but renaming to customer ID is still important. An extra issue for that is requested! :+1:

**Comment by dnil** [comment] 2019-01-18 07:39
I can't remember creating any; so since you ask.. :wink:
Thank you!

**Comment by henrikstranneheim** [comment] 2019-06-20 06:28
@emiliaol Did you open a new issue? If could you please link it to this issue.

**Comment by emiliaol** [comment] 2019-09-11 09:25
@henrikstranneheim Nope, I can't recall doing that, but here it is: Clinical-Genomics/cg#426. Closing this issue

**Closed by emiliaol** 2019-09-11 09:25 UTC
Labels: PBL Team <teamname>
