### ISSUE TITLE
Bug: Not possible to filter for `Pending` status in Balsamic tab of the Order view

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/cg#3456] opened 2024-07-23 08:42 UTC
**Describe the bug**

When trying to filter Balsamic orders with `Pending` status, the following error occurs:

```shell
Something went wrong in the backend
Request failed with status code 500 https://cg-statusdb.scilifelab.se/api/v1/orders?workflow=balsamic&search=&pageSize=20&page=1&delivered=false
```

**To Reproduce**
1. Filter for `Pending` status in Balsamic tab of the Order view.

**Expected behavior**
Orders with `Pending` status are shown.

**Additional context**
It is possible to filter for `Delivered` orders in the Balsamic tab and none of the other tabs seem to be affected.

**Comment by islean** [comment] 2024-07-29 08:02
@beatrizsavinhas Is this still an issue? Tried it now, seemed to work.

**Comment by seallard** [comment] 2024-07-29 12:53
Pretty sure this is a duplicate of https://github.com/Clinical-Genomics/cigrid-ui/issues/664 which has been patched.

**Closed by seallard** 2024-07-29 12:53 UTC
Labels: Bug

**Comment by islean** [comment] 2024-07-29 12:56
Discussed this with BSV and although the root cause does not seem to be the "depending" filtering, there does seem to be an issue with some specific order not being rendered. I will open a new issue for it.
