### ISSUE TITLE
Clean up Fluffly delivery files

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cg#618] opened 2020-04-07 13:29 UTC
**When** 
**I want** 
**so that** 

#### Questions & Answer:
Q:
A:

**Comment by moonso** [comment] 2021-02-15 15:49
This needs more description @Mropat or @barrystokman , who is best suited to update?

**Comment by henrikstranneheim** [comment] 2021-02-18 09:24
@J35P312 @Mropat Is this done or what is left to do?

**Comment by Mropat** [comment] 2021-02-18 09:38
The delivery files aren't being cleaned right now. There is only one analysis to clean so far.

**Comment by henrikstranneheim** [comment] 2021-02-18 10:36
What does clean up mean in this aspect? Is this a duplicate of https://github.com/Clinical-Genomics/cg/issues/617 or there some parsing of the files that needs to take place? Could you add some more details (when you have time) to make it easier to understand what needs to be done

**Comment by henrikstranneheim** [comment] 2021-06-07 08:07
Resolved

**Closed by henrikstranneheim** 2021-06-07 08:07 UTC
Labels: Effort S, Gain S, NIPT NovaSeq, Urgency S, WIP
